<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4a081e23-757a-43be-9166-fd8da3aa4003</testSuiteGuid>
   <testCaseLink>
      <guid>ff4bd788-cb63-4b54-9ecd-03a4c96ea715</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FindAPlace</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e80df08f-0eee-4b74-8717-259186ded712</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/citylistexcel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e80df08f-0eee-4b74-8717-259186ded712</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>city</value>
         <variableId>ac446bee-789f-4654-b591-c50b23ff426a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e80df08f-0eee-4b74-8717-259186ded712</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>b7cb6d68-cc9c-432b-8149-72e649f68917</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
